name: Deploy Infra-3Tierbuild

on:
  push:
    branches:
      - main
  #workflow_dispatch:  # 👈 Manual trigger from GitHub UI

jobs:
  terraform-Apply:
    name: "Terraform plan and Apply"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (Remote Backend)
        run: terraform init
        
      - name: Terraform format fix
        run: terraform fmt -recursive
        
      - name: Terraform Format Chek
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate
        
      - name: terraform plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan.out
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan.out
